### ISSUE TITLE
Warn when inconsistent names are used for `fetch-content`

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#108]
```toml
[fetch-content.zydis]
git = "https://github.com/zyantific/zasm"
```

This should warn the user that the project name `zasm` does not match the content name `zydis`
