### ISSUE TITLE
Add `SYSTEM` support for `fetch-content`

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#110]
```toml
[fetch-content.blah]
git = "https://github.com/blah/blah"
tag = "v1.0"
system = true
```

This requires:

```
[cmake]
version = "3.25"
```

Documentation: https://cmake.org/cmake/help/latest/module/FetchContent.html
