### ISSUE TITLE
Error if `cmkr-include` is the wrong type or not found

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#126]
```toml
[cmake]
version = "3.15"
cmkr-include = ["cmake/cmkr.cmake"]
```

This silently removes the cmkr include from the `CMakeLists.txt` instead of erroring. Only an empty string/false should do that.
