### ISSUE TITLE
Conditional `headers` causes weird error

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#130]
```toml
# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "myproject"

[options]
PROJECT_OPTION = false

[target.riscvm]
type = "executable"
sources = ["project.cpp"]
headers = ["project.h"]
PROJECT_OPTION.headers = ["option.h"]
```
