### ISSUE TITLE
Make sure the hash value is hex

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#152]
```toml
[fetch-content.json]
url = "https://github.com/nlohmann/json/releases/download/v3.11.3/json.tar.xz"
sha256 = "invalidhex"
```

This will always raise an error at configure-time:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/ExternalProject.cmake:3089 (message):
  URL_HASH is set to

    SHA256=invalidhex

  but must be ALGO=value where ALGO is

    MD5|SHA1|SHA224|SHA256|SHA384|SHA512|SHA3_224|SHA3_256|SHA3_384|SHA3_512

  and value is a hex string.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/ExternalProject.cmake:4465 (_ep_add_download_command)
  CMakeLists.txt:21 (ExternalProject_Add)
```
