### ISSUE TITLE
Implement seamless packaging

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#16]
Ideally writing

```toml
[project]
name = "example"
version = "1.0"

[find-package]
fmt = {}

[target.mylib]
type = "static"
sources = ["..."]
link-libraries = ["fmt::fmt"]

[target.otherlib]
type = "static"
sources = ["..."]

[target.mytool]
type = "static"
sources = ["..."]
link-libraries = ["mylib", "otherlib"]

[package]
targets = ["mylib", "otherlib", "mytool"]
dependency-packages = ["fmt"]
```

Should automatically generate a modern CMake package with a config file that has `IMPORTED` targets, versioning and the relevant `find_package` calls.
