### ISSUE TITLE
Linking to a directory causes an error with cmake

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#166]
```toml
[target.mylib]
type = "static"
sources = ["mylib/lib.cpp"]

[target.foo]
type = "executable"
sources = ["main.cpp"]
link-libraries = ["mylib"]
```

If `$(pwd)/mylib` is a directory CMake will (foolishly) attempt to link to a directory (wtf) and error out.
