### ISSUE TITLE
Confusing error message for source files with a space

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#172]
```toml
[target.foo]
type = "executable"
sources = ["main.cpp "]
```

It prints 'source file not found: main.cpp ', but you do not see the space in the terminal.
