### ISSUE TITLE
Add predefined conditions for `shared` and `static`

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#176]
```toml
[conditions]
shared = "BUILD_SHARED_LIBS"
static = "NOT BUILD_SHARED_LIBS"
```
