### ISSUE TITLE
Redo `[variables]`

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#178]
Currently specifying cache variables is a huge pain. The use case is variables that need to be set before the `project` call:

```cmake
set(CMAKE_CONFIGURATION_TYPES "Debug;Release" CACHE STRING "")
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")

project(x)
```

```toml
[variables]
CMAKE_BUILD_TYPE = { cache = "Release" }
CMAKE_CONFIGURATION_TYPES = { cache = "Debug;Release" }

[project]
name = "x"
```
