### ISSUE TITLE
Add an example with Objective-C and/or Swift

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#183]
```toml
apple.sources = ["src/platform_apple.mm"]
apple.link-libraries = [
    "$<LINK_LIBRARY:FRAMEWORK,Foundation>",
]
```
