### ISSUE TITLE
Add support for conditional languages

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#184]
```toml
[project]
name = "foo"
languages = ["C"]
apple.languages = ["OBJCXX"]
```

This should generate:

```cmake
project(foo LANGUAGES C)

if(<apple condition>)
  enable_language(OBJCXX)
endif()
```
