### ISSUE TITLE
Implement Windows kernel driver type

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#21]
```toml
[fetch-content]
FindWDK = { git = "https://github.com/SergiusTheBest/FindWDK" }

# TODO: inject ${FindWDK_SOURCE_DIR}/cmake in the CMAKE_MODULE_PATH

[find-package]
WDK = {}
```

Then generate:

```cmake
wdk_add_library(KmdfCppLib STATIC 
    KMDF 1.15
    WINVER 0x0602
    KmdfCppLib.h 
    KmdfCppLib.cpp
    )
```
