### ISSUE TITLE
Replace PMM with `vcpkg.json` generation + bootstrapping

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#23]
PMM is awfully complicated and does not work properly. Replace it with modern vcpkg.

```toml
[project]
name = "my_project"
version = "1.2"

[vcpkg]
version = "2021.05.12"
packages = ["fmt", "sqlite3"]
```

Should generate `vcpkg.json` (take care of the vcpkg identifiers not allowing capital letters or underscores):

```json
{
  "name": "vcpkg_template",
  "version": "0.0.1",
  "dependencies": ["fmt", "sqlite3"]
}
```

And (right after the `project`):

```cmake
include(FetchContent)

message(STATUS "Fetching vcpkg...")
FetchContent_Declare(
	vcpkg
	URL
		https://github.com/microsoft/vcpkg/archive/refs/tags/2021.05.12.tar.gz
)
FetchContent_MakeAvailable(vcpkg)

include(${vcpkg_SOURCE_DIR}/scripts/buildsystems/vcpkg.cmake)
```

See: https://github.com/build-cpp/vcpkg_template/tree/simplified-vscode. It also needs some kind of handling for subprojects (that scenario is not supported by vcpkg according to one of the authors) and it would be best if you get error messages that certain packages need to be specified in the root project for it to work.
