### ISSUE TITLE
Support object libraries

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#34]
```toml
[target.myobjectlib]
type = "object"
sources = ["src/*.cpp"]

[target.myexecutable]
type = "executable"
link-libraries = ["myobjectlib"]
```

This is supported since CMake 3.12
