### ISSUE TITLE
[options] should also be conditions

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#37]
Currently you need to do extra work:

```toml
[options]
PROJECT_BUILD_TESTS = false

[conditions]
tests = "PROJECT_BUILD_TESTS"

[target.tests]
condition = "tests"
sources = ["src/tests.cpp"]
```

This could be:

```toml
[options]
PROJECT_BUILD_TESTS = false

[target.tests]
condition = "PROJECT_BUILD_TESTS"
sources = ["src/tests.cpp"]
```
