### ISSUE TITLE
Error when recursively globbing in the root directory

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#48]
```toml
[project]
name = "myproject"

[target.foo]
type = "executable"
sources = ["**.cpp"]
```

This can include files downloaded/generated in the `build` directory and should error.
