### ISSUE TITLE
Settings variable containing special characters requires quotes

### ISSUE THREAD

**Issue by ZehMatt** [build-cpp/cmkr#54]
Having 
```toml
[settings]
MSVC_RUNTIME_LIBRARY = "MultiThreaded$<$<CONFIG:Debug>:Debug>"
```
Should generate:
```cmake
set(MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
```
instead of
```cmake
set(MSVC_RUNTIME_LIBRARY MultiThreaded$<$<CONFIG:Debug>:Debug>)
```
