### ISSUE TITLE
How can I pass one linker option on one platform and another for a different platform?

### ISSUE THREAD

**Issue by xtremegamer1** [build-cpp/cmkr#67]
I'm compiling VTIL with cmkr, and VTIL has absolutely obscene stack usage (1.4 megabytes in a single frame, and that's before even executing main!) so I need to use the linker flag for increasing stack size. Anyway am preparing to get a laptop with linux on it (because windows performance is intolerable on subpar hardware) so I would like a way that's cross platform and picks the relevant linker flag based on what compiler is chosen. tysm

**Comment by mrexodia** [comment]
You’re looking for “condition” in the reference.

**Comment by mrexodia** [comment]
The default conditions are:

[conditions]
windows = "WIN32"
macos = "CMAKE_SYSTEM_NAME MATCHES \"Darwin\""
unix = "UNIX"
bsd = "CMAKE_SYSTEM_NAME MATCHES \"BSD\""
linux = "CMAKE_SYSTEM_NAME MATCHES \"Linux\""
gcc = "CMAKE_CXX_COMPILER_ID STREQUAL \"GNU\" OR CMAKE_C_COMPILER_ID STREQUAL \"GNU\""
clang = "CMAKE_CXX_COMPILER_ID MATCHES \"Clang\" OR CMAKE_C_COMPILER_ID MATCHES \"Clang\""
msvc = "MSVC"
root = "CMKR_ROOT_PROJECT"
x64 = "CMAKE_SIZEOF_VOID_P EQUAL 8"
x32 = "CMAKE_SIZEOF_VOID_P EQUAL 4"

The list or cmake variables can be found at https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html

You can also use the [options] like so:

[options]
BUILD_TESTS = false

[conditions]
tests = “BUILD_TESTS”

[target.blah]
tests.compile-options = …

(on the phone so might be slightly wrong, but that’s the idea)

**Comment by mrexodia** [comment]
Ah and the missing part, you can control the `options` from the command line like so:

```
cmake -B build -DBUILD_TESTS=ON
```

**Comment by xtremegamer1** [comment]
So if a command comes after <condition>. then it will be executed conditionally?  I see, to me that reminds me of struct member resolution and not conditional statement. But, that may be because i have never used scripting languages like json before. Thank you for your help, cmkr #1 :)

**Comment by mrexodia** [comment]
Yeah, the format `<condition>.key` is supported in all places you would expect. The exception is conditional targets and subdirectories (basically there is no `[<condition>.section]`, those have a `condition` key to prevent impossible scenarios):

```toml
[conditions]
tests = "..." # see above

# Only build the my-tests target when the `tests` condition evaluates to true
[target.my-tests]
condition = "tests"
type = "executable"
sources = ["*.cpp"]

# Similar with subdirectories, only include the "tests" subdirectory when building with tests
[subdir.tests]
condition = "tests"
```

I agree this is a bit unintuitive initially, but there is no such thing as a conditional in TOML so this is the workaround.
