### ISSUE TITLE
Error when there are no source files added for the specified language

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#87]
```toml
[project]
name = "blah"

[target.foo]
type = "executable"
```

This will cause an error at generation time, because `foo` does not have any sources so CMake cannot determine which linker to use. It's important to look for `.cpp` `.c` files, headers would not trigger a language detection in CMake either.
