### ISSUE TITLE
Warn when using an unknown language

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#89]
Currently if you do:

```toml
[project]
languages = ["Nonsense"]
```

There is no error. At the very least this should warn. Related: https://gitlab.kitware.com/cmake/cmake/-/issues/24340
